sudo: required
services: 
  - docker

before_install:
  - docker build -t jlaws/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run jlaws/react-test npm run test -- --coverage

after_success:
  - docker built -t jlaws/multi-client ./client
  - docker built -t jlaws/multi-nginx ./nginx
  - docker built -t jlaws/multi-server ./server  
  - docker built -t jlaws/multi-worker ./worker
  # Log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hun
  - docker push jlaws/multi-client
  - docker push jlaws/multi-nginx
  - docker push jlaws/multi-server
  - docker push jlaws/multi-worker
