sudo: required
services: 
  - docker

before_install:
  - docker build -t jlaws/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run jlaws/react-test npm run test -- --coverage

after_success:
  - docker build -t jlaws/multi-client ./client
  - docker build -t jlaws/multi-nginx ./nginx
  - docker build -t jlaws/multi-server ./server  
  - docker build -t jlaws/multi-worker ./worker
  # Log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hun
  - docker push jlaws/multi-client
  - docker push jlaws/multi-nginx
  - docker push jlaws/multi-server
  - docker push jlaws/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-241763169723
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY